#!/bin/bash

files=$(unbuffer git status -s \
        | fzf --ansi --multi \
            --preview='tmp={};git difftool -y --extcmd="difft --color=always --display=inline" HEAD -- ${tmp:3}' \
            --preview-window='75%' \
        | awk '{print $2}' \
        | tr '\n' ' ')

if [[ -n "$files" ]]; then
    # shellcheck disable=SC2086
    git add $files
else
    exit 1
fi
