#!/usr/bin/env bash

set -eux

export SCRIPTPATH
SCRIPTPATH="$( cd "$(dirname "$0")" && pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "${SCRIPTPATH}/down" /tmp/leftwm-theme-down

leftwm-command "LoadTheme ${SCRIPTPATH}/theme.ron"

# picom
picom --config "${SCRIPTPATH}/picom.conf" &

# wallpaper
feh --no-fehbg --randomize --bg-fill ~/.local/wallpapers/*

# eww
sleep 1
eww open bar
