#!/bin/bash

set -eux

_select_name() {
    "${HOME}/.config/sway/scripts/get-simpletree" \
    | jq -r '.nodes |= map(.name) | .nodes |= join(",") | {name, nodes} | join(": ")' \
    | wofi --dmenu \
    | cut -d: -f1
}

_main() {
    local name
    name=$(_select_name)
    if [[ -n $name ]]; then
        swaymsg workspace "${name}"
    fi
}

_main
