[helpers]

[common.variables]
fontsize = 13

[common.files]
"home/.config/alacritty/alacritty.yml" = "~/.config/alacritty/alacritty.yml"
"home/.config/autostart/fcitx5.desktop" = "~/.config/autostart/fcitx5.desktop"
"home/.config/bat/config" = "~/.config/bat/config"
"home/.config/common.env" = "~/.config/common.env"
"home/.config/eww/bar/Cargo.lock" = "~/.config/eww/bar/Cargo.lock"
"home/.config/eww/bar/Cargo.toml" = "~/.config/eww/bar/Cargo.toml"
"home/.config/eww/bar/eww.scss" = "~/.config/eww/bar/eww.scss"
"home/.config/eww/bar/eww.yuck" = "~/.config/eww/bar/eww.yuck"
"home/.config/eww/bar/src" = "~/.config/eww/bar/src"
"home/.config/eww/powermenu" = "~/.config/eww/powermenu"
"home/.config/fcitx5/config" = "~/.config/fcitx5/config"
"home/.config/fcitx5/profile" = { target = "~/.config/fcitx5/profile", type = "template" }
"home/.config/git/config" = "~/.config/git/config"
"home/.config/git/gitmessage" = "~/.config/git/gitmessage"
"home/.config/git/script" = "~/.config/git/script"
"home/.config/gtk-3.0/settings.ini" = "~/.config/gtk-3.0/settings.ini"
"home/.config/i3/config" = "~/.config/i3/config"
"home/.config/nushell/env.nu" = "~/.config/nushell/env.nu"
"home/.config/nushell/config.nu" = "~/.config/nushell/config.nu"
"home/.config/nvim/init.lua" = "~/.config/nvim/init.lua"
"home/.config/nvim/lazy-lock.json" = "~/.config/nvim/lazy-lock.json"
"home/.config/nvim/lua" = "~/.config/nvim/lua"
"home/.config/rofi/config.rasi" = "~/.config/rofi/config.rasi"
"home/.config/rofi/themes/nord.rasi" = "~/.config/rofi/themes/nord.rasi"
"home/.config/sheldon/plugins.toml" = "~/.config/sheldon/plugins.toml"
"home/.config/starship.toml" = "~/.config/starship.toml"
"home/.config/sway/config" = "~/.config/sway/config"
"home/.config/swaylock/config" = "~/.config/swaylock/config"
"home/.config/tmux/tmux.conf" = "~/.config/tmux/tmux.conf"
"home/.config/wofi/style.css" = "~/.config/wofi/style.css"
"home/.config/zabrze/config.yaml" = "~/.config/zabrze/config.yaml"
"home/.config/zsh/.zshenv" = "~/.config/zsh/.zshenv"
"home/.config/zsh/.zshrc" = "~/.config/zsh/.zshrc"
"home/.local/bin/tmux-change-session" = "~/.local/bin/tmux-change-session"
"home/.local/share/icons/default/index.theme" = "~/.local/share/icons/default/index.theme"
"home/.zshenv" = "~/.zshenv"

[root.files]
"files/greetd/config.toml" = { target = "/etc/greetd/config.toml", type = "template", owner = "root" }
"files/greetd/regreet.toml" = { target = "/etc/greetd/regreet.toml", type = "template", owner = "root" }
"files/i3/i3.desktop" = { target = "/usr/share/xsessions/i3-script.desktop", type = "template", owner = "root" }
"files/i3/xinitrc" = { target = "/etc/X11/xinit/xinitrc-script", type = "template", owner = "root" }
"files/sway/sway-start.sh" = { target = "/usr/local/bin/sway-start.sh", type = "template", owner = "root" }
"files/sway/sway.desktop" = { target = "/usr/share/wayland-sessions/sway-script.desktop", type = "template", owner = "root" }
