[helpers]

[common.variables]
fontsize = 13

[common.files]
"home/.config/alacritty/alacritty.yml" = "~/.config/alacritty/alacritty.yml"
"home/.config/autostart/fcitx5.desktop" = "~/.config/autostart/fcitx5.desktop"
"home/.config/bat/config" = "~/.config/bat/config"
"home/.config/common.env" = "~/.config/common.env"
"home/.config/eww/bar/Cargo.lock" = "~/.config/eww/bar/Cargo.lock"
"home/.config/eww/bar/Cargo.toml" = "~/.config/eww/bar/Cargo.toml"
"home/.config/eww/bar/eww.scss" = "~/.config/eww/bar/eww.scss"
"home/.config/eww/bar/eww.yuck" = "~/.config/eww/bar/eww.yuck"
"home/.config/eww/bar/src" = "~/.config/eww/bar/src"
"home/.config/eww/powermenu" = "~/.config/eww/powermenu"
"home/.config/fcitx5/config" = "~/.config/fcitx5/config"
"home/.config/fcitx5/profile" = { target = "~/.config/fcitx5/profile", type = "template" }
"home/.config/git/config" = "~/.config/git/config"
"home/.config/git/gitmessage" = "~/.config/git/gitmessage"
"home/.config/git/script" = "~/.config/git/script"
"home/.config/gtk-3.0/settings.ini" = "~/.config/gtk-3.0/settings.ini"
"home/.config/hypr" = "~/.config/hypr"
"home/.config/nushell/env.nu" = "~/.config/nushell/env.nu"
"home/.config/nushell/config.nu" = "~/.config/nushell/config.nu"
"home/.config/nvim/init.lua" = "~/.config/nvim/init.lua"
"home/.config/nvim/lazy-lock.json" = "~/.config/nvim/lazy-lock.json"
"home/.config/nvim/lua" = "~/.config/nvim/lua"
"home/.config/starship.toml" = "~/.config/starship.toml"
"home/.config/swaylock/config" = "~/.config/swaylock/config"
"home/.config/tmux/tmux.conf" = "~/.config/tmux/tmux.conf"
"home/.config/wofi/style.css" = "~/.config/wofi/style.css"
"home/.local/bin/tmux-change-session" = "~/.local/bin/tmux-change-session"
"home/.local/share/icons/default/index.theme" = "~/.local/share/icons/default/index.theme"

[root.files]
"files/greetd/config.toml" = { target = "/etc/greetd/config.toml", type = "template", owner = "root" }
"files/greetd/regreet.toml" = { target = "/etc/greetd/regreet.toml", type = "template", owner = "root" }
