[helpers]

[default]
depends = []

[default.files]

[default.variables]

[zsh.files]
"files/zsh/zshenv" = "~/.zshenv"
"files/zsh/zshrc" = "~/.config/zsh/.zshrc"
"files/starship/starship.toml" = "~/.config/starship.toml"
