[helpers]

[default]
depends = []

[default.files]

[default.variables]

[zsh.files]
"files/zsh/zshenv" = "~/.zshenv"
"files/zsh/zshrc" = "~/.config/zsh/.zshrc"
"files/starship/starship.toml" = "~/.config/starship.toml"
"files/tmux/tmux.conf" = "~/.config/tmux/tmux.conf"
"files/tmux/status-line" = "~/.config/tmux/status-line"

[git.files]
"files/git/gitconfig" = "~/.config/git/config"

[qtile.files]
"files/qtile/config.py" = "~/.config/qtile/config.py"

[alacritty.files]
"files/alacritty/alacritty.yml" = "~/.config/alacritty/alacritty.yml"

[micro.files]
"files/micro/settings.json" = "~/.config/micro/settings.json"
