[helpers]

[common.files]
"files/common.env" = "~/.config/common.env"

[cui-common]
depends = ["git", "neovim", "zsh"]

[gui-common]
depends = ["alacritty", "qutebrowser", "theme"]

[alacritty]
variables = { fontsize = "13" }
[alacritty.files]
"files/alacritty/alacritty.yml" = "~/.config/alacritty/alacritty.yml"

[bat.files]
"files/bat/config" = "~/.config/bat/config"

[emacs.files]
"files/emacs/init.el" = "~/.config/emacs/init.el"
"files/emacs/init-org.org" = "~/.config/emacs/init-org.org"

[eww.files]
"files/eww/eww.yuck" = "~/.config/eww/eww.yuck"
"files/eww/eww.scss" = "~/.config/eww/eww.scss"

[fcitx5.files]
"files/fcitx5/config" = "~/.config/fcitx5/config"
"files/fcitx5/profile" = { target = "~/.config/fcitx5/profile", type = "template" }
"files/fcitx5/fcitx5.desktop" = "~/.config/autostart/fcitx5.desktop"

[fzf.files]
"bin/fzf-float" = "~/.local/bin/fzf-float"

[git.files]
"files/git/gitconfig" = "~/.config/git/config"
"files/git/gitmessage" = "~/.config/git/gitmessage"
"files/git/script" = "~/.config/git/script"

[greetd.files]
"files/greetd/config.toml" = { target = "/etc/greetd/config.toml", type = "template", owner = "root" }

[i3]
depends = ["fcitx5", "rofi"]
[i3.files]
"files/i3/config" = "~/.config/i3/config"
"files/i3/i3.desktop" = { target = "/usr/share/xsessions/i3-script.desktop", type = "template", owner = "root" }
"files/i3/xinitrc" = { target = "/etc/X11/xinit/xinitrc-script", type = "template", owner = "root" }

[leftwm]
depends = ["eww", "fcitx5", "greetd", "rofi"]
[leftwm.files]
"files/leftwm/config.ron" = "~/.config/leftwm/config.ron"
"files/leftwm/theme" = "~/.config/leftwm/themes/current"
"files/leftwm/leftwm-start.sh" = { target = "/usr/local/bin/leftwm-start.sh", type = "template", owner = "root" }
"files/leftwm/leftwm.desktop" = { target = "/usr/share/xsessions/leftwm-script.desktop", type = "template", owner = "root" }

[micro.files]
"files/micro/settings.json" = "~/.config/micro/settings.json"

[neovim.files]
"files/neovim/init.lua" = "~/.config/nvim/init.lua"
"files/neovim/lazy-lock.json" = "~/.config/nvim/lazy-lock.json"

[paru.files]
"files/paru/paru.conf" = "~/.config/paru/paru.conf"

[qtile.files]
"files/qtile/config.py" = "~/.config/qtile/config.py"
"bin/qtile-switch-group" = "~/.local/bin/qtile-switch-group"

[qutebrowser.files]
"files/qutebrowser/autoconfig.yml" = "~/.config/qutebrowser/autoconfig.yml"
"files/qutebrowser/config.py" = "~/.config/qutebrowser/config.py"
"files/qutebrowser/nord-qutebrowser.py" = "~/.config/qutebrowser/nord-qutebrowser.py"
"files/qutebrowser/greasemonkey" = "~/.local/share/qutebrowser/greasemonkey"

[rofi.files]
"files/rofi/nord.rasi" = "~/.config/rofi/themes/nord.rasi"
"files/rofi/config.rasi" = "~/.config/rofi/config.rasi"

[starship.files]
"files/starship/starship.toml" = "~/.config/starship.toml"

[sway]
depends = ["greetd", "waybar", "wofi"]
[sway.files]
"files/sway/sway-start.sh" = { target = "/usr/local/bin/sway-start.sh", type = "template", owner = "root" }
"files/sway/sway.desktop" = { target = "/usr/share/wayland-sessions/sway-script.desktop", type = "template", owner = "root" }
"files/sway/config" = "~/.config/sway/config"
"files/sway/scripts" = "~/.config/sway/scripts"
"bin/random-wallpaper" = "~/.local/bin/random-wallpaper"

[theme.files]
"files/theme/index.theme" = "~/.local/share/icons/default/index.theme"
"files/theme/settings.ini" = "~/.config/gtk-3.0/settings.ini"

[tmux.files]
"files/tmux/tmux.conf" = "~/.config/tmux/tmux.conf"
"bin/tmux-change-session" = "~/.local/bin/tmux-change-session"

[vivid.files]
"files/vivid/filetypes.yml" = "~/.config/vivid/filetypes.yml"

[waybar.files]
"files/waybar/config" = "~/.config/waybar/config"
"files/waybar/style.css" = "~/.config/waybar/style.css"

[wofi.files]
"files/wofi/style.css" = "~/.config/wofi/style.css"

[zabrze.files]
"files/zabrze/config.yaml" = "~/.config/zabrze/config.yaml"

[zsh]
depends = ["common", "bat", "fzf", "starship", "tmux", "vivid", "zabrze"]
[zsh.files]
"files/zsh/home.zshenv" = "~/.zshenv"
"files/zsh/.zshenv" = "~/.config/zsh/.zshenv"
"files/zsh/.zshrc" = "~/.config/zsh/.zshrc"
"files/zsh/plugins.toml" = "~/.config/sheldon/plugins.toml"
