[helpers]

[default]
depends = []

[default.files]
"files/common.env" = "~/.config/common.env"

[default.variables]

[zsh]
depends = ["default"]

[zsh.files]
"files/zsh/home.zshenv" = "~/.zshenv"
"files/zsh/zshenv" = "~/.config/zsh/.zshenv"
"files/zsh/zshrc" = "~/.config/zsh/.zshrc"
"files/zsh/scripts/fzf-select-files" = "~/.config/zsh/scripts/fzf-select-files"
"files/starship/starship.toml" = "~/.config/starship.toml"
"files/tmux/tmux.conf" = "~/.config/tmux/tmux.conf"
"bin/chse" = "~/.local/bin/chse"
"files/bat/config" = "~/.config/bat/config"

[git.files]
"files/git/gitconfig" = "~/.config/git/config"
"files/git/fzf-gadd" = "~/.config/git/script/fzf-gadd"
"bin/emoji-commit" = "~/.local/bin/emoji-commit"

[qtile.files]
"files/qtile/config.py" = "~/.config/qtile/config.py"
"bin/qtile-switch-group" = "~/.local/bin/qtile-switch-group"

[alacritty.files]
"files/alacritty/alacritty.yml" = "~/.config/alacritty/alacritty.yml"
"bin/fzf-float" = "~/.local/bin/fzf-float"
[alacritty.variables]
fontsize = "13"

[micro.files]
"files/micro/settings.json" = "~/.config/micro/settings.json"

[fcitx5.files]
"files/fcitx5/config" = "~/.config/fcitx5/config"
"files/fcitx5/profile" = { target = "~/.config/fcitx5/profile", type = "template" }
"files/fcitx5/xprofile" = "~/.xprofile"

[i3.files]
"files/i3/config" = "~/.config/i3/config"
"files/i3/i3.desktop" = { target = "/usr/share/xsessions/i3-script.desktop", type = "template", owner = "root"}
"files/i3/xinitrc" = { target = "/etc/X11/xinit/xinitrc-script", type = "template", owner = "root"}

[sway.files]
"files/sway/sway-start.sh" = { target = "/usr/local/bin/sway-start.sh", type = "template", owner = "root" }
"files/sway/sway.desktop" = { target = "/usr/share/wayland-sessions/sway-script.desktop", type = "template", owner = "root" }
"files/sway/config" = "~/.config/sway/config"
"bin/sway-get-simpletree" = "~/.local/bin/sway-get-simpletree"
"bin/sway-switch-workspace" = "~/.local/bin/sway-switch-workspace"
"files/waybar/config" = "~/.config/waybar/config"
"files/waybar/style.css" = "~/.config/waybar/style.css"
"files/wofi/style.css" = "~/.config/wofi/style.css"

[emacs.files]
"files/emacs/init.el" = "~/.config/emacs/init.el"
"files/emacs/init-org.org" = "~/.config/emacs/init-org.org"

[pacman.files]
"files/paru/paru.conf" = "~/.config/paru/paru.conf"

[greetd.files]
"files/greetd/config.toml" = { target = "/etc/greetd/config.toml", type= "template", owner = "root" }
