[helpers]

[common.files]
"files/common.env" = "~/.config/common.env"

[cui-common]
depends = ["git", "neovim", "zsh"]

[gui-common]
depends = ["alacritty", "theme"]

[alacritty]
variables = { fontsize = "13" }
[alacritty.files]
"files/alacritty/alacritty.yml" = "~/.config/alacritty/alacritty.yml"

[bat.files]
"files/bat/config" = "~/.config/bat/config"

[fcitx5.files]
"files/fcitx5/config" = "~/.config/fcitx5/config"
"files/fcitx5/profile" = { target = "~/.config/fcitx5/profile", type = "template" }
"files/fcitx5/fcitx5.desktop" = "~/.config/autostart/fcitx5.desktop"

[git.files]
"files/git/gitconfig" = "~/.config/git/config"
"files/git/gitmessage" = "~/.config/git/gitmessage"
"files/git/script" = "~/.config/git/script"

[greetd.files]
"files/greetd/config.toml" = { target = "/etc/greetd/config.toml", type = "template", owner = "root" }

[i3]
depends = ["fcitx5", "rofi"]
[i3.files]
"files/i3/config" = "~/.config/i3/config"
"files/i3/i3.desktop" = { target = "/usr/share/xsessions/i3-script.desktop", type = "template", owner = "root" }
"files/i3/xinitrc" = { target = "/etc/X11/xinit/xinitrc-script", type = "template", owner = "root" }

[neovim.files]
"files/neovim/init.lua" = "~/.config/nvim/init.lua"
"files/neovim/lazy-lock.json" = "~/.config/nvim/lazy-lock.json"
"files/neovim/lua" = "~/.config/nvim/lua"

[rofi.files]
"files/rofi/nord.rasi" = "~/.config/rofi/themes/nord.rasi"
"files/rofi/config.rasi" = "~/.config/rofi/config.rasi"

[starship.files]
"files/starship/starship.toml" = "~/.config/starship.toml"

[sway]
depends = ["greetd", "wofi"]
[sway.files]
"files/sway/sway-start.sh" = { target = "/usr/local/bin/sway-start.sh", type = "template", owner = "root" }
"files/sway/sway.desktop" = { target = "/usr/share/wayland-sessions/sway-script.desktop", type = "template", owner = "root" }
"files/sway/config" = "~/.config/sway/config"
"files/sway/eww" = "~/.config/sway/eww"

[theme.files]
"files/theme/index.theme" = "~/.local/share/icons/default/index.theme"
"files/theme/settings.ini" = "~/.config/gtk-3.0/settings.ini"

[tmux.files]
"files/tmux/tmux.conf" = "~/.config/tmux/tmux.conf"
"bin/tmux-change-session" = "~/.local/bin/tmux-change-session"

[wofi.files]
"files/wofi/style.css" = "~/.config/wofi/style.css"

[zabrze.files]
"files/zabrze/config.yaml" = "~/.config/zabrze/config.yaml"

[zsh]
depends = ["common", "bat", "starship", "tmux", "zabrze"]
[zsh.files]
"files/zsh/home.zshenv" = "~/.zshenv"
"files/zsh/.zshenv" = "~/.config/zsh/.zshenv"
"files/zsh/.zshrc" = "~/.config/zsh/.zshrc"
"files/zsh/plugins.toml" = "~/.config/sheldon/plugins.toml"
