[helpers]

[default]
depends = []

[default.files]
"files/common.env" = "~/.config/common.env"

[default.variables]

[zsh]
depends = ["default"]

[zsh.files]
"files/zsh/home.zshenv" = "~/.zshenv"
"files/zsh/zshenv" = "~/.config/zsh/.zshenv"
"files/zsh/zshrc" = "~/.config/zsh/.zshrc"
"files/zsh/scripts/fzf-select-files" = "~/.config/zsh/scripts/fzf-select-files"
"files/starship/starship.toml" = "~/.config/starship.toml"
"files/tmux/tmux.conf" = "~/.config/tmux/tmux.conf"
"bin/chse" = "~/.local/bin/chse"
"files/bat/config" = "~/.config/bat/config"

[git.files]
"files/git/gitconfig" = "~/.config/git/config"
"bin/emoji-commit" = "~/.local/bin/emoji-commit"

[qtile.files]
"files/qtile/config.py" = "~/.config/qtile/config.py"
"bin/qtile-switch-group" = "~/.local/bin/qtile-switch-group"

[alacritty.files]
"files/alacritty/alacritty.yml" = "~/.config/alacritty/alacritty.yml"
"bin/fzf-float" = "~/.local/bin/fzf-float"
[alacritty.variables]
fontsize = "13"

[micro.files]
"files/micro/settings.json" = "~/.config/micro/settings.json"

[fcitx5.files]
"files/fcitx5/config" = "~/.config/fcitx5/config"
"files/fcitx5/profile" = { target = "~/.config/fcitx5/profile", type = "template" }
"files/fcitx5/xprofile" = "~/.xprofile"

[i3.files]
"files/i3/config" = "~/.config/i3/config"

[sway.files]
"files/sway/config" = "~/.config/sway/config"
"files/waybar/config" = "~/.config/waybar/config"
"files/waybar/style.css" = "~/.config/waybar/style.css"

[emacs.files]
"files/emacs/init.el" = "~/.config/emacs/init.el"
"files/emacs/init-org.org" = "~/.config/emacs/init-org.org"
