includes = []
packages = [
    "common",
    "cui-common",
#        "git",
#        "neovim",
#        "zsh",
    "gui-common",
#        "alacritty",
#        "qutebrowser",
    # window managers
    "i3",
    "leftwm",
    "sway",
    # other
    "emacs",
    "micro",
    "paru",
    "qtile",

    # deps
#    "bat",
#    "bitwarden",
#    "eww",
#    "fcitx5",
#    "fzf",
#    "greetd",
#    "rofi",
#    "starship",
#    "tmux",
#    "vivid",
#    "waybar",
#    "wofi",
#    "zabrze",
]

[files]

[variables]
#fontsize = "11" # alacritty font size
