includes = []
packages = [
    "common",
    "cui-common",
    #        "git",
    #        "neovim",
    #        "zsh",
    "gui-common",
    #        "alacritty",
    # window managers
    "i3",
    "sway",
    # other
    "paru",

    # deps
    #    "bat",
    #    "fcitx5",
    #    "greetd",
    #    "rofi",
    #    "starship",
    #    "tmux",
    #    "wofi",
    #    "zabrze",
]

[files]

[variables]
#fontsize = "11" # alacritty font size
